### ISSUE TITLE
"Vorper" Text in Opera/Opera GX

### ISSUE THREAD

**Issue by Nym1edit** [VorperTeam/Vorper#1]
The "Vorper" text gets "censored" when viewing the page in Opera or Opera GX
![okdZcam](https://github.com/VorperTeam/Vorper/assets/149179687/0a3e336f-330e-4d70-aced-cf31340e9e1d)

**Comment by PH7N** [comment]
Was fixed. Clear the cache of the website in said broswer.

**Comment by 4B026** [comment]
Fixed![IMG_20231231_194939.png](https://github.com/VorperTeam/Vorper/assets/155258124/17e14d08-2899-405a-acb8-addc3a771e65)
